### ISSUE TITLE
Unity Ads rewarded video sometimes doesn't fire OnRewardedVideoReceivedRewardEvent

### ISSUE THREAD

**Issue by muxapet** [mopub/mopub-unity-mediation#22] opened 2018-11-28 12:56 UTC
I try to show Unity Ads rewarded placement through mediation on Android device, but I don't receive callbacks if I try to show two videos one after another. I load the second one from OnRewardedVideoClosedEvent after first video was closed. Second video appears and when I close it, I don't receive any callback (neither OnRewardedVideoClosedEvent, nor OnRewardedVideoReceivedRewardEvent). If I try to load one more video, I get error:
```
MoPub   : Did not queue rewarded ad request for ad unit ..... The ad is already showing.
```

Also, if I don't receive callbacks, I don't see this lines in log:
```
MoPub   : Unity Ad finished with finish state = COMPLETED
MoPub   : Unity rewarded video completed for placement reward
MoPub   : Sending message to Unity: MoPubManager#EmitRewardedVideoReceivedRewardEvent["....","","-123"]
MoPub   : Sending message to Unity: MoPubManager#EmitRewardedVideoClosedEvent["...."]
```

Unity version 5.6.4f1
MoPubSDKVersion 5.4.0
mopub-unityads-adapters-3.0.0.0
unity-ads 3.0.0

**Comment by chauduyphanvu1** [comment] 2018-11-28 16:31
Hi @muxapet,

We might be looking at more than 1 issues based on your observed behavior.

 > Second video appears and when I close it, I don't receive any callback (neither OnRewardedVideoClosedEvent, nor OnRewardedVideoReceivedRewardEvent)

How consistent are you not getting callbacks for your second video? Do the other callbacks fire for your second video? If so, what are they? The expectation is that you should be getting all callbacks for all videos. Feel free to send across a Unity project so we can take a closer look.

> If I try to load one more video, I get error:
MoPub   : Did not queue rewarded ad request for ad unit ..... The ad is already showing.

Is that ad unit ID the same as the one used in your previous two ad requests? If so, there is currently a bug that will be fixed in a future SDK release. The SDK thinks the current video is still "active". For now, try to delay the next ad request by a few ms (maybe 10), so the SDK has time to mark the current video as played, and let us know if you see that log again. This workaround is only needed if your ad requests use the same ad unit ID.

Vu Chau
MoPub SDK Team

**Comment by muxapet** [comment] 2018-11-29 07:53
Thank you @chauduyphanvu1 for answer.

> How consistent are you not getting callbacks for your second video? Do the other callbacks fire for your second video? If so, what are they?

This problem appears every second time when I try to show the same MoPub rewarded placemenent with same Unity Ads placement (rewardedVideo).
I have made sample unity project with test ad identifiers. I get first rewarded video loaded, and I get callbacks well.
After that I reload placement and get `MoPubManager#EmitRewardedVideoLoadedEvent[""]`.
After watching second video I don't receive any callbacks (you can see it because counters and time don't change).

[Mopub-sample.zip](https://github.com/mopub/mopub-unity-mediation/files/2628107/Mopub-sample.zip)
[mopub-sample.apk.zip](https://github.com/mopub/mopub-unity-mediation/files/2628113/mopub-sample.apk.zip)

> Is that ad unit ID the same as the one used in your previous two ad requests?

Yes, ad unit ID is the same.

**Comment by chauduyphanvu1** [comment] 2018-11-29 16:40
Thanks for sending over the project. I'll take a look and get back with any findings.

Meanwhile, the second issue should have already been fixed in the 5.4.1 release yesterday. Check it out and let us know!

**Comment by chauduyphanvu1** [comment] 2018-11-29 21:48
@muxapet, are you able to send over a debug build? Your attached project appears to be a release build and I'm asked to provide a signing password. If not, could you paste some relevant code snippets here or modify our Unity sample project to do the same?

I rewrote our [Unity sample app](https://s3.us-east-2.amazonaws.com/chauduyphanvu/github/mopub-unity-mediation/22/mopub-unity-sdk.zip) to make serial ad requests and I was able to get all callbacks for each video. Could you try your ad unit ID in that sample app?

**Comment by chauduyphanvu1** [comment] 2018-12-11 23:11
@muxapet - thanks for the help with reproducing the issue. It looks like this issue is happening only **with the Unity Ads** rewarded video adapters **for apps built from Unity**. Callbacks for the second video are lost, so any subsequent video thereafter won't automatically play (because there's no more close callback):

```
2018-12-11 17:56:51.267 21280-21280/? D/MoPub: : MoPubManager#EmitRewardedVideoLoadedEvent["2b6e890452654f5695cf2bf2969ceb74"]
2018-12-11 17:56:51.775 21280-21280/? D/MoPub: : MoPubManager#EmitRewardedVideoShownEvent["2b6e890452654f5695cf2bf2969ceb74"]
2018-12-11 17:57:01.209 21280-21280/? D/MoPub: : MoPubManager#EmitRewardedVideoReceivedRewardEvent["2b6e890452654f5695cf2bf2969ceb74","","-123"]
2018-12-11 17:57:01.209 21280-21280/? D/MoPub: : MoPubManager#EmitRewardedVideoClosedEvent["2b6e890452654f5695cf2bf2969ceb74"]
2018-12-11 17:57:01.394 21280-21280/? D/MoPub: : MoPubManager#EmitRewardedVideoLoadedEvent["2b6e890452654f5695cf2bf2969ceb74"]
```
I replicated the test on Android and all Unity Ads videos played without this problem:

```
2018-12-11 17:53:53.162 20634-20634/ D/MoPub: onRewardedVideoLoadSuccess for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:53:53.766 20634-20634/ D/MoPub: onRewardedVideoStarted for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:54:03.639 20634-20634/ D/MoPub: onRewardedVideoCompleted for ad unit ID [2b6e890452654f5695cf2bf2969ceb74]
2018-12-11 17:54:03.648 20634-20634/ D/MoPub: onRewardedVideoClosed for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:54:03.849 20634-20634/ D/MoPub: onRewardedVideoLoadSuccess for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:54:06.865 20634-20634/ D/MoPub: onRewardedVideoStarted for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:54:17.573 20634-20634/ D/MoPub: onRewardedVideoCompleted for ad unit ID [2b6e890452654f5695cf2bf2969ceb74]
2018-12-11 17:54:17.581 20634-20634/ D/MoPub: onRewardedVideoClosed for ad unit ID 2b6e890452654f5695cf2bf2969ceb74
2018-12-11 17:54:18.578 20634-20634/ D/MoPub: onRewardedVideoLoadSuccess for ad unit ID 412408b08ee945a59659d03844acba4f
2018-12-11 17:54:18.779 20634-20634/ D/MoPub: onRewardedVideoStarted for ad unit ID 412408b08ee945a59659d03844acba4f
2018-12-11 17:54:48.666 20634-20634/ D/MoPub: onRewardedVideoCompleted for ad unit ID [412408b08ee945a59659d03844acba4f]
2018-12-11 17:55:15.747 20634-20634/ D/MoPub: onRewardedVideoClosed for ad unit ID 412408b08ee945a59659d03844acba4f
```

I'm going to investigate some more. In the meantime, let us know if you see this issue with rewarded video adapters from other networks, too!

**Comment by shake1050** [comment] 2019-01-09 13:07
same issue，unity ads can‘t get callback after the second play！does it fixed now？

**Comment by chauduyphanvu1** [comment] 2019-01-09 15:31
@shake1050 - we're still investigating this issue. Let us know if you also see this issue with ads from other mediation networks and/or on other platforms.

**Comment by MixMasterRickyC** [comment] 2019-01-11 11:09
Hey, I wasn't sure whether or not to open a new issue as it's very similar to this one.

It only seems to affect iOS devices and only on the first launch. I'm not 100% sure but it also only seems to affect Unity adverts.

On the first advert shown the VideoShownEvent, VideoReceivedRewardEvent and VideoClosedEvent are never fired. 

We also track adverts have been played via a server side response and this also isn't being hit.

Is there anything you need from me logs wise to help track this issue down.

Currently running MoPub 5.4.0 with Unity Adverts 2.3.0

**Comment by mubshar1** [comment] 2019-01-18 15:23
same issue

**Comment by chauduyphanvu1** [comment] 2019-01-23 20:48
We are working on a fix for this. If you aren't sure your issue is the identical to this one, please open a separate issue report and attach a repro project so we can investigate. Thanks!

**Comment by chauduyphanvu1** [comment] 2019-01-24 21:15
The issue reported in https://github.com/mopub/mopub-unity-mediation/issues/22#issue-385255744 has been fixed and will be released in the upcoming Unity Ads adapter release. Once the fix is in production, you should be able to request multiple Unity Ads creatives in a row with all listeners intact.

If you see callback-related issues with adapters from _other network(s)_ and/or on another platform, please open a new issue report.

**Comment by chauduyphanvu1** [comment] 2019-01-31 17:41
This issue is fixed in https://github.com/mopub/mopub-unity-mediation/commit/bb086b3dacd8ae8168255ffa64bc544a7dd5c975. Please try again with the latest Unity Ads .unitypackage binary (MoPub-UnityAds-Adapters-prod-1.0.0-Android.3.0.0.1-iOS.3.0.0.3.unitypackage) and let us know if the issue persists!

**Closed by chauduyphanvu1** 2019-01-31 17:41 UTC
Labels: bug

**Comment by JasmineSun2018** [comment] 2019-02-14 03:53
@chauduyphanvu1 Pls correct the NetworkSdkVersions in UnityAdsPackageConfig.cs, it's still using 3.0.0 and causing publishers not receiving reward callbacks. Many thanks.
`public override Dictionary<Platform, string> NetworkSdkVersions
    {
        get {
            return new Dictionary<Platform, string> {
                { Platform.ANDROID, "3.0.0" },
                { Platform.IOS, "3.0.0" }
            };
        }
    }`
