### ISSUE TITLE
AndroidX-related crashes because the MoPub SDK looks for non-AndroidX v4 support library

### ISSUE THREAD

**Issue by mubshar1** [mopub/mopub-unity-mediation#40] opened 2019-06-21 12:03 UTC
1. **What is the issue?**
    > Crash FATAL EXCEPTION: main

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > all
    * **Platform** (*Android, iOS, Unity*)
        > Unity
    * **MoPub SDK Version**
        > 5.7.1
    * **Mediation SDK Name & Version**
        > Admob, Unity, Facebook, IronSource, Chartboost
    * **Mediation Adapter Version**
        > all latest
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Crash on start
    * **Device model and OS Version**
        > All Devices
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Build App
        > 2. Run on Android
    * **Observed behavior**
        > Crash
    * **Expected behavior** (if known)
        > Crash
    * **Evidence** (if available)
        > Attach logs (d
![mopuberrr](https://user-images.githubusercontent.com/45542019/59921237-8581ab00-9446-11e9-8126-5b147db8b892.PNG)
evice/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu1** [comment] 2019-06-21 14:03
@mubshar1, the stack trace seems to be saying your project does not have the Android v4 support library in it. Are you integrating MoPub via [MoPub's SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#option-1-use-the-sdk-manager-recommended) or are you doing it manually? If you use the SDK Manager, we should automatically download the v4 library for you. If you are integrating manually, you will need to download it yourself (you can find it in `\extras\android\m2repository\com\android\support\support-v4 ` of your Android SDK's download directory) and place it in `Assets/Plugins/Android`.

Vu Chau
MoPub SDK Team

**Comment by mubshar1** [comment] 2019-06-21 14:44
Android v4 support library is already present in the project, named as "androidx.legacy:legacy-support-v4:1.0.0"

**Comment by chauduyphanvu1** [comment] 2019-06-21 18:05
Could you try [enabling the Jetifier](https://developer.android.com/jetpack/androidx/migrate#migrate) in Gradle to convert the v4 support library to its AndroidX equivalent?

**Comment by mubshar1** [comment] 2019-06-22 04:38
> Could you try [enabling the Jetifier](https://developer.android.com/jetpack/androidx/migrate#migrate) in Gradle to convert the v4 support library to its AndroidX equivalent?

How is it possible in Unity?

**Comment by mubshar1** [comment] 2019-06-22 05:52
Actually, I'm using Admob and Mopub plugin both of them in the project. 
There is an option in Android Resolver Settings "Use Jetifier" (see SS attached); Without enabling this option build always fail, By enabling this option build got successful but Crash on initializing Mopub (as I describe above).
![mopunerrr](https://user-images.githubusercontent.com/45542019/59960078-d2639100-94db-11e9-9125-115af1ab964a.PNG)

**Comment by chauduyphanvu1** [comment] 2019-06-24 14:24
@mubshar1, thank you for the details. Did you manually place the AndroidX v4 library (`androidx.legacy:legacy-support-v4:1.0.0`) in your project or was it dynamically downloaded by another SDK? If you use the SDK Manager, MoPub should be downloading the non-AndroidX version of the v4 library. I'm trying to reproduce the issue but so far haven't been able to get any AndroidX library.

**Comment by mubshar1** [comment] 2019-06-25 03:10
@chauduyphanvu use the latest version of play-services-resolver-1.2.119.0, You will face the same problem.

**Comment by chauduyphanvu** [comment] 2019-06-25 13:31
@mubshar1, thanks for the confirmation. We're still testing with AndroidX internally, so we will have more updates soon. Stay tuned! 

For now, which MoPub SDK and which AdMob adapter versions are you integrating? We did not get AndroidX dependencies when integrating with MoPub 5.7.1 and AdMob 17.2.1.0, unless there are other dependencies in your project that force the Jar Resolver to go for Play services 18.0.0, getting AndroidX dependencies transitively.

**Comment by mubshar1** [comment] 2019-06-26 04:06
@chauduyphanvu  Currently I'm using MoPub 5.7.1 and AdMob 18.0.0.

**Comment by chauduyphanvu** [comment] 2019-06-26 15:31
@mubshar1, AdMob 18.0.0 is _not_ certified ([see certified versions](https://developers.mopub.com/publishers/mediation/integrate/)) and that version is pulling AndroidX aar's to your project. While we are working on addressing compatibility with AndroidX, I recommend rolling your AdMob version to 17.2.1 (and 17.2.1.x for adapters).

Check out [this Jar Resolver issue](https://github.com/googlesamples/unity-jar-resolver/issues/241) as well for more info.

**Comment by mubshar1** [comment] 2019-07-02 07:59
@chauduyphanvu, any update regarding compatibility with AndroidX?

**Comment by chauduyphanvu** [comment] 2019-07-02 13:56
Thanks for checking in! Currently there's no update yet, and the team is still investigating. Timeline-wise, AndroidX changes probably won't make it into the SDK release that's coming up (but maybe the one after it).

**Comment by shanukp** [comment] 2019-07-15 09:14
Facebook audience network latest is also pulling androidx dependencies

**Comment by shanukp** [comment] 2019-07-15 09:23
to which version of fbaudience network should we go ?

**Comment by chauduyphanvu** [comment] 2019-07-15 20:50
@shanukp, we've ensured compatibility with AndroidX internally and you will get that benefit in the upcoming MoPub Unity SDK release. For now, we do not have recommendations on which version of the Facebook Audience Network SDK to use, as there can be unpredicted version conflicts with existing SDKs, and you could still end up with AndroidX packages in your project.

**Comment by JimmyDeemo** [comment] 2019-07-18 14:02
I too would be interested in when AndroidX compatible UnitySDK will be released.

**Comment by chauduyphanvu** [comment] 2019-07-19 04:36
@JimmyDeemo, we will not be officially supporting AndroidX in the upcoming MoPub Unity SDK release because the underlying MoPub Android SDK will not yet use AndroidX libraries.

**Comment by JimmyDeemo** [comment] 2019-07-22 10:30
Forgive me but isn't this a problem with how the underlying code/dll accesses the support libraries? I am using the Jetifier setting yet still get `NoClassDefFoundError` errors for classes that are referenced by the old package name.

I get this issue with Facebook's SDK as well as MoPub. Perhaps i'm not fully understanding the problem here. For example, please can you explain to me how existing SDK's referencing `com.support.v4.content.LocalBroadcastManager` should be looking in the androidx .aar rather than the older one? Do you know of any documention for this?

**Comment by JimmyDeemo** [comment] 2019-07-23 12:43
Also, please can you tell me if there is a workaround for this until the SDK is released? We are tied into AndroidX for the Jar Resolver due to other plugins in the project.

**Comment by JimmyDeemo** [comment] 2019-07-24 15:00
I have discovered that our project wasn't using the jetifier correctly, meaning that packages were not being mapped to thei AndroidX equivolents.

**Comment by rsatrasala** [comment] 2019-07-24 19:49
Hello @JimmyDeemo please let us know if the updated use of jetifier corrected the problem.

In any case, we are releasing the new version of our Unity plugin 5.8 this week and I recommend using 5.8 to get over jetifier issues.

**Comment by JimmyDeemo** [comment] 2019-07-25 14:12
Yes. After correctly updating the Play Service resolver and configuring it to use the Jetifier I no longer receive any errors associated with MoPub support classes. If anyone stumbles on this, you can see my settings here; https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514995546.

**Comment by mubshar1** [comment] 2019-07-30 14:33
> Yes. After correctly updating the Play Service resolver and configuring it to use the Jetifier I no longer receive any errors associated with MoPub support classes. If anyone stumbles on this, you can see my settings here; [googlesamples/unity-jar-resolver#241 (comment)](https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514995546).

**Comment by mubshar1** [comment] 2019-07-30 14:33
> Yes. After correctly updating the Play Service resolver and configuring it to use the Jetifier I no longer receive any errors associated with MoPub support classes. If anyone stumbles on this, you can see my settings here; [googlesamples/unity-jar-resolver#241 (comment)](https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514995546).

**Comment by mubshar1** [comment] 2019-07-30 14:34
@JimmyDeemo  Thank You Brother , this worked for me.  perfect answer

**Comment by chauduyphanvu** [comment] 2019-07-30 14:35
The MoPub Unity SDK 5.8.0 has been released, and it contains the new Play Services Resolver that has the Jetifier to resolve AndroidX conflicts. Please update to 5.8.0, [enable the Jetifier](https://developers.mopub.com/publishers/unity/get-started/), and let us know if you continue seeing the issue!

**Comment by mubshar1** [comment] 2019-07-30 14:36
@chauduyphanvu  problem is still there

**Closed by chauduyphanvu** 2019-07-30 14:35 UTC

**Comment by chauduyphanvu** [comment] 2019-07-30 15:17
@mubshar1, what is the problem you are seeing with the 5.8.0 MoPub Unity SDK? What are the steps to reproduce the issue and what is the error message? We need more details in order to help you.

**Comment by mubshar1** [comment] 2019-07-30 17:15
@chauduyphanvu 

1) import unity package MoPubUnity 
2) Enable 'Use Jetifier' in play services resolver settings.
2) Resolve Android dependencies 
3) Build with MoPubDemoScene
4) Install and Run Application
5) Crash

**Comment by chauduyphanvu** [comment] 2019-07-30 17:17
@mubshar1, could you provide us the stack trace?

Also, it sounds like you are not using mediation, so it's possibly you do not have any AndroidX packages in your project. In that case, make sure you actually do not use the Jetifier (disable it), and run the app again ([docs](https://developers.mopub.com/publishers/unity/get-started/)). The Jetifier should only be enabled if there are AndroidX packages in your project, and it should be turned off otherwise.

**Comment by mubshar1** [comment] 2019-07-30 17:23
@chauduyphanvu  Solution 
1) import unity package MoPubUnity
2) Enable 'Use Jetifier' on in your play services resolver settings.
3) Resolve Android dependencies
4) create and manually patch the 'mainTemplate.gradle' file in your project to add the following just above apply plugin: 'com.android.application';

```
([rootProject] + (rootProject.subprojects as List)).each {
	ext {
		it.setProperty("android.useAndroidX", true)
		it.setProperty("android.enableJetifier", true)
	}
}
```
5) add the following line to your build script dependencies if you are using anything less than Unity 2019.1.7f1 :

```
buildscript {
	repositories {
		google()
		jcenter()
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:3.2.1'
		classpath 'com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02' //Jetifier workaround
	}
}
```
6) Build with MoPubDemoScene
7) Install and Run Application

**Comment by mubshar1** [comment] 2019-07-30 17:27
> @mubshar1, could you provide us the stack trace?
> 
> Also, it sounds like you are not using mediation, so it's possibly you do not have any AndroidX packages in your project. In that case, make sure you actually do not use the Jetifier (disable it), and run the app again ([docs](https://developers.mopub.com/publishers/unity/get-started/)). The Jetifier should only be enabled if there are AndroidX packages in your project, and it should be turned off otherwise.

see SS attached 
![err](https://user-images.githubusercontent.com/45542019/62151191-323e2a80-b319-11e9-93c0-07fc701fedf5.PNG)

**Comment by chauduyphanvu** [comment] 2019-07-30 19:27
We saw this crash internally at some point, and were able to resolve it by disabling the Jetifier and calling Play Services Resolver's `Force Resolve` option. You do not have to take the long route described in https://github.com/mopub/mopub-unity-mediation/issues/40#issuecomment-516514202.

**Comment by vizgl** [comment] 2019-08-05 17:45
Got same crash, I am use Firebase. When I manuaaly disable Jetifier it automatically enabled when click force resolve

**Comment by chauduyphanvu** [comment] 2019-08-07 22:09
@vizgl, are you still seeing that issue where the Jetifier gets re-enabled after you click on `Force Resolve`? I did not reproduce that on my end (the Jetifier remains disabled).

**Comment by SelcukSZR** [comment] 2019-09-07 13:14
This problem still occurs. Also if you have AndroidX libraries in your project, disabling Jetifier and making force resolve makes Jetifier enabled again automatically. We are unable to publish any updates for our games any more coz of this util.pair error. It seems for some reason Jetifier couldnt jetify "import android.support.v4.util.Pair" command in MoPubLog.java file. I will give JimmyDeemo's solution a try.

**Comment by chauduyphanvu** [comment] 2019-09-09 15:45
@SelcukSZR, we've fixed this issue internally and made things more convenient for AndroidX-based integrations. You should be able to get the fix in the upcoming SDK release. Stay tuned!

**Comment by SelcukSZR** [comment] 2019-09-09 15:49
@chauduyphanvu Happy to hear that, thanks for your effort.

**Comment by tink3rla** [comment] 2019-09-15 19:36
Hi, is there a timeframe for release of the fix from MoPub side, or suggested workaround?

**Comment by chauduyphanvu** [comment] 2019-09-15 23:40
@tink3rla, barring any technical issues, we are targeting this week for the release. Keep an eye out for the new SDK release!

**Comment by mubshar1** [comment] 2019-09-16 03:15
> We saw this crash internally at some point, and were able to resolve it by disabling the Jetifier and calling Play Services Resolver's `Force Resolve` option. You do not have to take the long route described in [#40 (comment)](https://github.com/mopub/mopub-unity-mediation/issues/40#issuecomment-516514202).

@chauduyphanvu  Everything is working fine by simply Enabling the "Jetifier" and "Patch mainTemplate.gradle"  and calling Play Services Resolver's "Force Resolve"
