### ISSUE TITLE
IronSource mediation issue

### ISSUE THREAD

**Issue by naronov12343** [mopub/mopub-unity-mediation#38] opened 2019-05-26 16:07 UTC
1. **What is the issue?**
    Ironsource adapter not started. An Activity Context is needed

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x ] I searched https://developers.mopub.com/ and found no answer.
    - [ x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Interstitial, Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        Unity
    * **MoPub SDK Version**
        5.7.0
    * **Mediation SDK Name & Version**
        IronSource
    * **Mediation Adapter Version**
        1.1.7
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        Interstitial: 93a8c529d948400591826cb3cfd5becc
        Rewarded: c809e06bda474730a266bca39e67b863
    * **Device model and OS Version**
        Samsung Galaxy A8 Star, Android 8.0
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Install MoPub SDK
        > 2. Install IronSource Adapter and IronSource SDK
        > 3. Write the following code

var anyAdUnitId = bannerAdUnit[0];
MoPub.InitializeSdk(new MoPub.SdkConfiguration
        {
            AdUnitId = anyAdUnitId,
            LogLevel = MoPubBase.LogLevel.MPLogLevelDebug,
            MediatedNetworks = new MoPub.MediatedNetwork[]
            {
                new MoPub.SupportedNetwork.IronSource()
            },
        });
 MoPub.LoadBannerPluginsForAdUnits(bannerAdUnit);
        MoPub.LoadInterstitialPluginsForAdUnits(interstitialId);
        MoPub.LoadRewardedVideoPluginsForAdUnits(rewardedId);

    * **Observed behavior**
        Ironsource adapter not started. An Activity Context is needed
05-26 18:17:17.070 I/MoPub   (15428): [com.mopub.common.BaseAdapterConfiguration][getCachedInitializationParameters] SDK Log - fetched init settings for 1 networks: [com.mopub.mobileads.IronSourceAdapterConfiguration]
05-26 18:17:17.071 I/MoPub   (15428): [com.mopub.common.BaseAdapterConfiguration][setCachedInitializationParameters] SDK Log - Updating init settings for custom event com.mopub.mobileads.IronSourceAdapterConfiguration with params {"appKey":"com.fasterxml.jackson.jr.stree.JrsString@36d757"}
05-26 18:17:17.071 I/MoPub   (15428): [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log - Initializing com.mopub.mobileads.IronSourceAdapterConfiguration version 6.8.4.0 with network sdk version 6.8.4 and with params {appKey=com.fasterxml.jackson.jr.stree.JrsString@36d757}
05-26 18:17:17.072 I/MoPub   (15428): [com.mopub.mobileads.IronSourceAdapterConfiguration][initializeNetwork] Adapter IronSourceAdapterConfiguration Log - IronSource's initialization via IronSourceAdapterConfiguration not started. An Activity Context is needed.
05-26 18:17:17.075 I/MoPub   (15428): [com.mopub.common.AdapterConfigurationManager][onNetworkInitializationFinished] SDK Log - class com.mopub.mobileads.IronSourceAdapterConfiguration initialized with error code Native Network or Custom Event adapter was configured incorrectly.
05-26 18:17:17.149 I/MoPub   (15428): IronSourceAdapterConfiguration: Adapter version 6.8.4.0, SDK version 6.8.4

    * **Expected behavior** (if known)
        Sdk initialization
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.
[logcat (1).txt](https://github.com/mopub/mopub-unity-mediation/files/3220503/logcat.1.txt)

**Comment by dravyan** [comment] 2019-05-28 18:11
@naronov12343 ,
 Thank you for reporting this. The log message what you are seeing `IronSource adapter not started. An Activity Context is needed` is intended behavior and not really an error. The MoPub SDK initializes supported network SDKs on-demand on app start. The context at this time is an Application context, however, so it will skip initializing the IronSource SDK since IronSource requires an Activity context. This is not a fatal failure, because network SDKs will initialize lazily at the time of the ad request. Hence the log message is informational only.
Also, I notice that you are using below snippet during initialization. Please note that you need to pass in required key/value (if applicable). Otherwise, the below snippet is not needed. Refer to the example shown [here](https://developers.mopub.com/publishers/unity/initialize/#example).
```
MediatedNetworks = new MoPub.MediatedNetwork[]
{
new MoPub.SupportedNetwork.IronSource()
},
});
```

Thanks,
Dravya Nataraj

**Comment by chauduyphanvu1** [comment] 2019-06-07 14:16
Closing due to intended behavior. Feel free to re-open if needed.

**Closed by chauduyphanvu1** 2019-06-07 14:16 UTC
