### ISSUE TITLE
Fatal Exception: java.lang.InternalError

### ISSUE THREAD

**Issue by Armen101** [mopub/mopub-unity-mediation#42] opened 2019-11-18 07:41 UTC
Fatal Exception: java.lang.InternalError
Thread starting during runtime shutdown
java.lang.Thread.nativeCreate (Thread.java)
android.os.AsyncTask.execute (AsyncTask.java:560)
com.ironsource.mediationsdk.events.BaseEventsManager.sendEvents (BaseEventsManager.java:292)
com.ironsource.mediationsdk.events.BaseEventsManager.access$1400 (BaseEventsManager.java:43)
com.ironsource.mediationsdk.events.BaseEventsManager$1.run (BaseEventsManager.java:209)

   Ad Formats - Banner, Interstitial, Rewarded Video
   Platform - Android
   MoPub SDK Version - 5.10.0
   Ironsource SDK version - 6.10.2
   OS Versions - 7, 8, 9

**Comment by hmertkahraman** [comment] 2019-11-18 17:59
Hi @Armen101 ,

Thanks for reporting this in addition to [issue 364](https://github.com/mopub/mopub-android-sdk/issues/364) on our Android repo. 

Similar to [our request from you on that issue](https://github.com/mopub/mopub-android-sdk/issues/364#issuecomment-555132994), can you also please share exact reproduction steps, and the stack trace of the crash (and ad unit ids if involved)?

Moreover, the error raised on [issue 364](https://github.com/mopub/mopub-android-sdk/issues/364) is the same: `Fatal Exception: java.lang.InternalError `. If possible, can you also please clarify if there are any link between these two issues you're reporting?

Thanks,
MoPub Team

**Comment by Armen101** [comment] 2019-11-19 13:39
Hi Hikmet, thanks for your reply. Unfortunately, I can't give you more information because I have gotten this from Crash tracking tools, on my end the crash was not reproduced. But I sent you log files.

**Comment by Armen101** [comment] 2019-11-19 13:51
`
#0. Crashed: ISEventThread
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker + 975(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute + 1382(ThreadPoolExecutor.java:1382)
       at android.os.AsyncTask$SerialExecutor.scheduleNext + 258(AsyncTask.java:258)
       at android.os.AsyncTask$SerialExecutor.execute + 252(AsyncTask.java:252)
       at android.os.AsyncTask.executeOnExecutor + 651(AsyncTask.java:651)
       at android.os.AsyncTask.execute + 595(AsyncTask.java:595)
       at com.ironsource.mediationsdk.events.BaseEventsManager.sendEvents + 292(BaseEventsManager.java:292)
       at com.ironsource.mediationsdk.events.BaseEventsManager.access$1400 + 43(BaseEventsManager.java:43)
       at com.ironsource.mediationsdk.events.BaseEventsManager$1.run + 209(BaseEventsManager.java:209)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)

--

Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker + 975(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute + 1382(ThreadPoolExecutor.java:1382)
       at android.os.AsyncTask$SerialExecutor.scheduleNext + 258(AsyncTask.java:258)
       at android.os.AsyncTask$SerialExecutor.execute + 252(AsyncTask.java:252)
       at android.os.AsyncTask.executeOnExecutor + 651(AsyncTask.java:651)
       at android.os.AsyncTask.execute + 595(AsyncTask.java:595)
       at com.ironsource.mediationsdk.events.BaseEventsManager.sendEvents + 292(BaseEventsManager.java:292)
       at com.ironsource.mediationsdk.events.BaseEventsManager.access$1400 + 43(BaseEventsManager.java:43)
       at com.ironsource.mediationsdk.events.BaseEventsManager$1.run + 209(BaseEventsManager.java:209)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)

#0. Crashed: ISEventThread
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker + 975(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute + 1382(ThreadPoolExecutor.java:1382)
       at android.os.AsyncTask$SerialExecutor.scheduleNext + 258(AsyncTask.java:258)
       at android.os.AsyncTask$SerialExecutor.execute + 252(AsyncTask.java:252)
       at android.os.AsyncTask.executeOnExecutor + 651(AsyncTask.java:651)
       at android.os.AsyncTask.execute + 595(AsyncTask.java:595)
       at com.ironsource.mediationsdk.events.BaseEventsManager.sendEvents + 292(BaseEventsManager.java:292)
       at com.ironsource.mediationsdk.events.BaseEventsManager.access$1400 + 43(BaseEventsManager.java:43)
       at com.ironsource.mediationsdk.events.BaseEventsManager$1.run + 209(BaseEventsManager.java:209)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)

#1. IronSourceInitiatorHandler
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next + 326(MessageQueue.java:326)
       at android.os.Looper.loop + 183(Looper.java:183)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)`

**Comment by rsatrasala** [comment] 2019-12-20 23:36
Closing due to lack of reproduction steps. Please reopen a new issue if needed

**Closed by rsatrasala** 2019-12-20 23:36 UTC
